<?php

namespace App\Observers;

use App\Events\GameStatusUpdated;
use App\Models\Game;
use App\Models\User;
use App\Notifications\UserGameStatusNotification;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Notification;
use Throwable;

class GameObserver
{
    public function updated(Game $game): void
    {
        $statusChanged = $game->wasChanged('status');
        $scoreChanged = $game->wasChanged(['home_score', 'away_score']);

        if (! $statusChanged && ! $scoreChanged) {
            return;
        }

        // User inbox must only include finished games with a defined final score.
        if ($game->status !== 'finished' || $game->home_score === null || $game->away_score === null) {
            return;
        }

        $notificationType = 'result';

        DB::afterCommit(function () use ($game, $notificationType) {
            try {
                $event = GameStatusUpdated::fromGame($game, $notificationType);

                if (! $this->shouldDispatchGameNotification($event->payload)) {
                    return;
                }

                broadcast($event);

                User::query()
                    ->where('is_admin', false)
                    ->select('id')
                    ->chunkById(200, function ($users) use ($event) {
                        Notification::send($users, new UserGameStatusNotification($event->payload));
                    });
            } catch (Throwable $e) {
                // Do not block score updates if websocket server is temporarily unavailable.
                Log::warning('Game broadcast failed', [
                    'game_id' => $game->id,
                    'status' => $game->status,
                    'notification_type' => $notificationType,
                    'error' => $e->getMessage(),
                ]);
            }
        });
    }

    private function shouldDispatchGameNotification(array $payload): bool
    {
        $gameId = $payload['gameId'] ?? null;
        $type = $payload['type'] ?? 'result';

        if (! $gameId) {
            return true;
        }

        $signature = md5(json_encode([
            'type' => $type,
            'status' => $payload['status'] ?? null,
            'homeScore' => $payload['homeScore'] ?? null,
            'awayScore' => $payload['awayScore'] ?? null,
            'matchDate' => $payload['matchDate'] ?? null,
            'matchTime' => $payload['matchTime'] ?? null,
            'venue' => $payload['venue'] ?? null,
            'homeTeam' => $payload['homeTeam'] ?? null,
            'awayTeam' => $payload['awayTeam'] ?? null,
        ]));

        $cacheKey = sprintf('game_notification:%s:%s', $gameId, $signature);

        // Ignore duplicates generated by repeated saves for the same logical update.
        return Cache::add($cacheKey, true, now()->addSeconds(90));
    }
}
